[package]
name = "SoS"
version = "0.2.0"
description = "The overlay that hunts you mid-stream — and turns every scare into a viral moment."
authors = ["BLACKLINE productions"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "sos_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-single-instance = "2"
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-autostart = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"


tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }


rand = "0.8"
tokio = { version = "1.53.1", features = ["full"] }
tiny_http = "0.12"
tokio-tungstenite = { version = "0.30.0", features = ["rustls-tls-webpki-roots"] }
futures-util = "0.3.33"
rustls = "0.23"
piratetok-live-rs = "0.2"

reqwest = { version = "0.12", features = ["json"] }
sha2 = "0.10"
base64 = "0.22"

[patch.crates-io]
piratetok-live-rs = { path = "vendor/piratetok-live-rs-0.2.1" }
